package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int ButtonRender = 1;
  public static final int ComponentRender = 2;
  public static final int IElementRender = 3;
  public static final int RApi = 4;
  public static final int RComponent = 5;
  public static final int REndPoint = 6;
  public static final int RInvetarDLS = 7;
  public static final int RShow = 8;
  public static final int RowRender = 9;
  public static final int TableRender = 10;
  public static final int TextRender = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd25897b99aa4e01L, 0x981001ea0072c283L);
    builder.put(0x2b90a9c731294b19L, Action);
    builder.put(0x2b90a9c731294b12L, ButtonRender);
    builder.put(0x2c7d7d2448d98c8bL, ComponentRender);
    builder.put(0x2c7d7d2448d98c95L, IElementRender);
    builder.put(0x2c7d7d2448d98cc4L, RApi);
    builder.put(0x2c7d7d2448d98c8eL, RComponent);
    builder.put(0x2c7d7d2448d98cc8L, REndPoint);
    builder.put(0x2c7d7d2448d98cddL, RInvetarDLS);
    builder.put(0x2c7d7d2448d98cd0L, RShow);
    builder.put(0x2b90a9c731294b0eL, RowRender);
    builder.put(0x505fed17fdfd5494L, TableRender);
    builder.put(0x2c7d7d2448d98cdaL, TextRender);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
