package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptButtonRender = createDescriptorForButtonRender();
  /*package*/ final ConceptDescriptor myConceptComponentRender = createDescriptorForComponentRender();
  /*package*/ final ConceptDescriptor myConceptIElementRender = createDescriptorForIElementRender();
  /*package*/ final ConceptDescriptor myConceptRApi = createDescriptorForRApi();
  /*package*/ final ConceptDescriptor myConceptRComponent = createDescriptorForRComponent();
  /*package*/ final ConceptDescriptor myConceptREndPoint = createDescriptorForREndPoint();
  /*package*/ final ConceptDescriptor myConceptRInvetarDLS = createDescriptorForRInvetarDLS();
  /*package*/ final ConceptDescriptor myConceptRShow = createDescriptorForRShow();
  /*package*/ final ConceptDescriptor myConceptRowRender = createDescriptorForRowRender();
  /*package*/ final ConceptDescriptor myConceptTextRender = createDescriptorForTextRender();
  /*package*/ final EnumerationDescriptor myEnumerationActionType = new EnumerationDescriptor_ActionType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptButtonRender, myConceptComponentRender, myConceptIElementRender, myConceptRApi, myConceptRComponent, myConceptREndPoint, myConceptRInvetarDLS, myConceptRShow, myConceptRowRender, myConceptTextRender);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.ButtonRender:
        return myConceptButtonRender;
      case LanguageConceptSwitch.ComponentRender:
        return myConceptComponentRender;
      case LanguageConceptSwitch.IElementRender:
        return myConceptIElementRender;
      case LanguageConceptSwitch.RApi:
        return myConceptRApi;
      case LanguageConceptSwitch.RComponent:
        return myConceptRComponent;
      case LanguageConceptSwitch.REndPoint:
        return myConceptREndPoint;
      case LanguageConceptSwitch.RInvetarDLS:
        return myConceptRInvetarDLS;
      case LanguageConceptSwitch.RShow:
        return myConceptRShow;
      case LanguageConceptSwitch.RowRender:
        return myConceptRowRender;
      case LanguageConceptSwitch.TextRender:
        return myConceptTextRender;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationActionType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Action", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b19L);
    b.class_(false, false, false);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3139195613265611545");
    b.version(3);
    b.property("type", 0x2b90a9c731294b1aL).type(MetaIdFactory.dataTypeId(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b1dL)).origin("3139195613265611546").done();
    b.property("url", 0x2b90a9c731294b1bL).type(PrimitiveTypeId.STRING).origin("3139195613265611547").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForButtonRender() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "ButtonRender", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b12L);
    b.class_(false, false, false);
    b.parent(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c95L);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3139195613265611538");
    b.version(3);
    b.property("text", 0x2b90a9c731294b14L).type(PrimitiveTypeId.STRING).origin("3139195613265611540").done();
    b.property("action", 0x5d8d0fa9f12f6c5eL).type(PrimitiveTypeId.STRING).origin("6741061439813807198").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponentRender() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "ComponentRender", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c8bL);
    b.class_(false, false, false);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172683");
    b.version(3);
    b.associate("cName", 0x2c7d7d2448d98c8dL).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c8eL).optional(false).origin("3205856104552172685").done();
    b.aggregate("elemRender", 0x2c7d7d2448d98c8cL).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c95L).optional(true).ordered(true).multiple(true).origin("3205856104552172684").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIElementRender() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "IElementRender", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c95L);
    b.interface_();
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172693");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRApi() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "RApi", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cc4L);
    b.class_(false, false, false);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172740");
    b.version(3);
    b.property("base", 0x2c7d7d2448d98cc5L).type(PrimitiveTypeId.STRING).origin("3205856104552172741").done();
    b.aggregate("endPointList", 0x2c7d7d2448d98cc6L).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cc8L).optional(true).ordered(true).multiple(true).origin("3205856104552172742").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRComponent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "RComponent", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c8eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172686");
    b.version(3);
    b.property("menu", 0x2c7d7d2448d98c92L).type(PrimitiveTypeId.BOOLEAN).origin("3205856104552172690").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForREndPoint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "REndPoint", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cc8L);
    b.class_(false, false, false);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172744");
    b.version(3);
    b.property("name", 0x2c7d7d2448d98cc9L).type(PrimitiveTypeId.STRING).origin("3205856104552172745").done();
    b.property("url", 0x2c7d7d2448d98ccaL).type(PrimitiveTypeId.STRING).origin("3205856104552172746").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRInvetarDLS() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "RInvetarDLS", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cddL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172765");
    b.version(3);
    b.property("dls_name", 0x2c7d7d2448d98ce0L).type(PrimitiveTypeId.STRING).origin("3205856104552172768").done();
    b.property("title", 0x2c7d7d2448d98ce1L).type(PrimitiveTypeId.STRING).origin("3205856104552172769").done();
    b.property("description", 0x2c7d7d2448d98ce3L).type(PrimitiveTypeId.STRING).origin("3205856104552172771").done();
    b.property("port", 0x2c7d7d2448d98ce4L).type(PrimitiveTypeId.INTEGER).origin("3205856104552172772").done();
    b.aggregate("listOfComponents", 0x2c7d7d2448d98ce5L).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c8eL).optional(true).ordered(true).multiple(true).origin("3205856104552172773").done();
    b.aggregate("api", 0x2c7d7d2448d98ce7L).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cc4L).optional(true).ordered(true).multiple(true).origin("3205856104552172775").done();
    b.aggregate("show", 0x2c7d7d2448d98ce8L).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cd0L).optional(true).ordered(true).multiple(true).origin("3205856104552172776").done();
    b.aggregate("renders", 0x2c7d7d2448d98ce9L).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c8bL).optional(true).ordered(true).multiple(true).origin("3205856104552172777").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRShow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "RShow", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cd0L);
    b.class_(false, false, false);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172752");
    b.version(3);
    b.property("navMenu", 0x2c7d7d2448d98cd1L).type(PrimitiveTypeId.BOOLEAN).origin("3205856104552172753").done();
    b.property("header", 0x2c7d7d2448d98cd2L).type(PrimitiveTypeId.BOOLEAN).origin("3205856104552172754").done();
    b.property("footer", 0x2c7d7d2448d98cd3L).type(PrimitiveTypeId.BOOLEAN).origin("3205856104552172755").done();
    b.property("text", 0x2c7d7d2448d98cd4L).type(PrimitiveTypeId.STRING).origin("3205856104552172756").done();
    b.property("theme", 0x2c7d7d2448d98cd5L).type(PrimitiveTypeId.STRING).origin("3205856104552172757").done();
    b.property("padding", 0x2c7d7d2448d98cd7L).type(PrimitiveTypeId.STRING).origin("3205856104552172759").done();
    b.property("showActiveItem", 0x2c7d7d2448d98cd8L).type(PrimitiveTypeId.BOOLEAN).origin("3205856104552172760").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRowRender() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "RowRender", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b0eL);
    b.class_(false, false, false);
    b.parent(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c95L);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3139195613265611534");
    b.version(3);
    b.property("clickable", 0x2b90a9c731294b0fL).type(PrimitiveTypeId.BOOLEAN).origin("3139195613265611535").done();
    b.property("action", 0x2b90a9c731294b21L).type(MetaIdFactory.dataTypeId(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b1dL)).origin("3139195613265611553").done();
    b.aggregate("cols", 0x2b90a9c731294b10L).target(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cdaL).optional(true).ordered(true).multiple(true).origin("3139195613265611536").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextRender() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "TextRender", 0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cdaL);
    b.class_(false, false, false);
    b.parent(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98c95L);
    b.origin("r:6c2c3770-ac97-4d60-a1d3-21d527b39f73(NewLanguage.structure)/3205856104552172762");
    b.version(3);
    b.property("text", 0x2c7d7d2448d98cdcL).type(PrimitiveTypeId.STRING).origin("3205856104552172764").done();
    return b.create();
  }
}
