package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ButtonRender_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<button action='");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.action$zFXK));
    tgs.append("'>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.text$VJAf));
    tgs.append("</button>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty action$zFXK = MetaAdapterFactory.getProperty(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b12L, 0x5d8d0fa9f12f6c5eL, "action");
    /*package*/ static final SProperty text$VJAf = MetaAdapterFactory.getProperty(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b12L, 0x2b90a9c731294b14L, "text");
  }
}
