package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RInvetarDLS_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    ctx.getBuffer().area().increaseIndent();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.listOfComponents$Tt_l)) {
      tgs.appendNode(item);
    }
    ctx.getBuffer().area().decreaseIndent();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink listOfComponents$Tt_l = MetaAdapterFactory.getContainmentLink(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cddL, 0x2c7d7d2448d98ce5L, "listOfComponents");
  }
}
