package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class RowRender_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("<row>");
    tgs.newLine();

    for (SNode colTextRender : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.cols$VDGU))) {
      tgs.indent();
      tgs.indent();
      tgs.append("<col>");
      tgs.append(SPropertyOperations.getString(colTextRender, PROPS.text$Tmxq));
      tgs.append("</col");
      tgs.newLine();
    }
    tgs.indent();
    tgs.append("</row>");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty text$Tmxq = MetaAdapterFactory.getProperty(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2c7d7d2448d98cdaL, 0x2c7d7d2448d98cdcL, "text");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink cols$VDGU = MetaAdapterFactory.getContainmentLink(0xd25897b99aa4e01L, 0x981001ea0072c283L, 0x2b90a9c731294b0eL, 0x2b90a9c731294b10L, "cols");
  }
}
